### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip' - line 124

### ISSUE THREAD

**Issue by pchaxor** [anonymous247742/TwitterReport#4]
http://t.co/6IdXk10JM7
https://t.co/UiyCAGcoZs

Traceback (most recent call last):
  File "twitterReport.py", line 133, in <module>
    main(sys.argv[1:])
  File "twitterReport.py", line 124, in main
    msg = url.strip()+' - CatchAllError'
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by anonymous247742** [comment]
Please use phrase for describe your problem,  i'm not a soothsayer.

Use twitter url on your file, because the script use regex to check url.
The script report twitter url, not facebook or other

**Comment by pchaxor** [comment]
Some twitter links do not work as given from feeds, I have been removing them.
This is problem with the format they are being given to us.

**Comment by pchaxor** [comment]
It is a problem with incorrect format from twitter feeds... I will manually correct it.
Also no way to feed from the lists here IS Tracker - Meine ASP.NET-Webseite
|   |
|   |  |   |   |   |   |   |
| IS Tracker - Meine ASP.NET-WebseiteIS Tracker. Welcome to the IS Tracker ! Feel free to use this page to impact damage to ISIS :)  |
|  |
| View on 50.31.234.10 | Preview by Yahoo |
|  |
|   |

```
On Sunday, November 22, 2015 10:22 AM, anonymous247742 <notifications@github.com> wrote:
```

 Please use phrase for describe your problem, i'm not a soothsayer.Use twitter url on your file, because the script use regex to check url.
The script report twitter url, not facebook or other—

**Comment by anonymous247742** [comment]
Fixed, https://github.com/anonymous247742/TwitterReport/commit/a3f23355193fd33b5bc0dda200c759099f575de0

**Comment by pchaxor** [comment]
This works great now!
Thank you!
